const wallets={latam:{name:"Latam (Outros)",short:"Latam",icon:"💳",limit:1107.40,hint:"Tudo que não for Swile entra aqui"},uber:{name:"Uber Trabalho — Swile",short:"Uber Trabalho",icon:"🚗",limit:320,hint:"Deslocamentos de trabalho"},almoco:{name:"Almoço Trabalho — Swile",short:"Almoço Trabalho",icon:"🍽️",limit:230,hint:"Almoços presenciais"},lazer:{name:"Lazer — Swile",short:"Lazer Swile",icon:"✨",limit:800,hint:"Uber pessoal, bebida, comida e rolês"}};
const categoryRules=[{key:"pets",label:"Pets",emoji:"🐱",words:["ração","racao","areia","pet","vet","veterin","golden","gran plus","premier","pipicat","chuck","lana","venus","hyoga","jason"]},{key:"delivery",label:"Delivery",emoji:"🍔",words:["ifood","99 food","99food","rappi","keeta","delivery","pizza","hamburg","lanche","sushi"]},{key:"mercado",label:"Mercado",emoji:"🛒",words:["assaí","assai","mercado","supermercado","atacad","pão de açúcar","pao de acucar","extra","carrefour"]},{key:"uber",label:"Uber",emoji:"🚗",words:["uber","99","taxi","táxi"]},{key:"farmacia",label:"Farmácia",emoji:"💊",words:["droga","farm","raia","drogasil","panvel","remédio","remedio"]},{key:"bebida",label:"Bebida",emoji:"🍻",words:["bebida","cerveja","ze delivery","zedelivery","vinho","bar","adega"]},{key:"assinaturas",label:"Assinaturas",emoji:"📺",words:["netflix","spotify","amazon","prime","apple","google","max","disney","crunchyroll"]}];
let expenses=JSON.parse(localStorage.getItem("tha_expenses_v1")||"[]");
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const walletCards=document.getElementById("walletCards"),walletSelect=document.getElementById("walletSelect"),expenseForm=document.getElementById("expenseForm"),descriptionInput=document.getElementById("descriptionInput"),amountInput=document.getElementById("amountInput"),expenseList=document.getElementById("expenseList"),categoryBreakdown=document.getElementById("categoryBreakdown"),insights=document.getElementById("insights"),toast=document.getElementById("toast"),resetMonthBtn=document.getElementById("resetMonthBtn");
function save(){localStorage.setItem("tha_expenses_v1",JSON.stringify(expenses))}function spentByWallet(k){return expenses.filter(e=>e.wallet===k).reduce((s,e)=>s+Number(e.amount),0)}
function getCategory(description,walletKey){if(walletKey==="uber")return{key:"uber",label:"Uber",emoji:"🚗"};if(walletKey==="almoco")return{key:"almoco",label:"Almoço trabalho",emoji:"🍽️"};if(walletKey==="lazer")return{key:"lazer",label:"Lazer Swile",emoji:"✨"};const n=description.toLowerCase();return categoryRules.find(r=>r.words.some(w=>n.includes(w)))||{key:"outros",label:"Outros Latam",emoji:"💳"}}
function renderWalletOptions(){walletSelect.innerHTML=Object.entries(wallets).map(([k,w])=>`<option value="${k}">${w.name}</option>`).join("")}
function renderWalletCards(){walletCards.innerHTML=Object.entries(wallets).map(([k,w])=>{const spent=spentByWallet(k),remaining=w.limit-spent,percent=Math.min(spent/w.limit*100,100);return`<article class="wallet-card"><div class="wallet-icon">${w.icon}</div><h3>${w.short}</h3><p class="remaining">${money.format(remaining)}</p><div class="meta">${money.format(spent)} de ${money.format(w.limit)}</div><div class="progress"><span style="width:${percent}%"></span></div><div class="meta">${Math.round(percent)}% usado</div></article>`}).join("")}
function renderTotals(){const limit=Object.values(wallets).reduce((s,w)=>s+w.limit,0),spent=expenses.reduce((s,e)=>s+Number(e.amount),0);document.getElementById("totalRemaining").textContent=money.format(limit-spent);document.getElementById("totalSpent").textContent=money.format(spent)}
function renderExpenses(){if(!expenses.length){expenseList.innerHTML=`<div class="empty">Nenhum gasto lançado ainda. Tha disciplinada por enquanto. 💜</div>`;return}expenseList.innerHTML=expenses.map(e=>{const w=wallets[e.wallet],c=getCategory(e.description,e.wallet);return`<div class="expense-row"><div class="expense-emoji">${c.emoji}</div><div><b>${e.description}</b><small>${e.date} • ${w.short}</small></div><div><b>${money.format(e.amount)}</b><button class="delete-btn" onclick="deleteExpense('${e.id}')" title="Excluir gasto">🗑</button></div></div>`}).join("")}
function renderCategories(){const totals={};expenses.forEach(e=>{const c=getCategory(e.description,e.wallet);if(!totals[c.key])totals[c.key]={...c,total:0};totals[c.key].total+=Number(e.amount)});const sorted=Object.values(totals).sort((a,b)=>b.total-a.total);categoryBreakdown.innerHTML=sorted.length?sorted.map(c=>`<div class="category-row"><div class="category-emoji">${c.emoji}</div><div><b>${c.label}</b><small>${c.key==="delivery"?"Esse é o que vamos vigiar 👀":"Total do mês"}</small></div><b>${money.format(c.total)}</b></div>`).join(""):`<div class="empty">Quando você lançar gastos, o app separa por categoria aqui.</div>`}
function renderInsights(){const latam=spentByWallet("latam"),delivery=expenses.filter(e=>getCategory(e.description,e.wallet).key==="delivery").reduce((s,e)=>s+Number(e.amount),0),uber=spentByWallet("uber"),lazer=spentByWallet("lazer"),msg=[];if(!expenses.length)msg.push("Começo limpo. Agora é só lançar sem medo, porque o app faz a conta por você.");else msg.push(`Latam está em ${Math.round(latam/wallets.latam.limit*100)}% do limite livre.`);if(delivery>0)msg.push(`Delivery já está em ${money.format(delivery)}. Ele não vai se esconder em “alimentação” aqui. 🍔`);if(uber>wallets.uber.limit*.8)msg.push("Uber Trabalho passou de 80% do teto. Hora de acender o alerta amarelo. 🚗");if(lazer>wallets.lazer.limit*.8)msg.push("Lazer Swile está chegando no limite. Sem julgamento, só sinalzinho roxo piscando. ✨");msg.push("Guardar R$ 1.500 é compromisso fixo do mês. Não é o que sobra: é prioridade. 💜");insights.innerHTML=msg.map(m=>`<div class="insight">${m}</div>`).join("")}
function renderDate(){document.getElementById("todayLabel").textContent=new Date().toLocaleDateString("pt-BR",{day:"2-digit",month:"long",year:"numeric"})}function render(){renderDate();renderWalletOptions();renderTotals();renderWalletCards();renderExpenses();renderCategories();renderInsights()}
function showToast(t="Gasto salvo 💜"){toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800)}
expenseForm.addEventListener("submit",e=>{e.preventDefault();const wallet=walletSelect.value,description=descriptionInput.value.trim(),amount=Number(amountInput.value);if(!description||!amount||amount<=0)return;expenses.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),wallet,description,amount,date:new Date().toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"})});save();expenseForm.reset();render();showToast()});
function deleteExpense(id){const expense=expenses.find(i=>i.id===id);if(!expense)return;if(!confirm(`Excluir "${expense.description}" de ${money.format(expense.amount)}?`))return;expenses=expenses.filter(i=>i.id!==id);save();render();showToast("Gasto excluído")}
resetMonthBtn.addEventListener("click",()=>{if(!confirm("Limpar todos os gastos lançados? Use só no fechamento/virada do mês."))return;expenses=[];save();render();showToast("Mês limpo")});render();
